services:
  backend:
    build: .
    env_file:
      - backend.env
    volumes:
      - ./keys:/keys:ro
      - uploads:/data
    depends_on: [postgres, redis]
    networks: [luna]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - frontend.env
    depends_on: [backend]
    networks: [luna]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/letsencrypt            # TLS cert volume
    ports:
      - "80:80"
      - "443:443"
    depends_on: [frontend, backend]
    networks: [luna]
